question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"},
    {"text": "An octopus has three hearts.", "answer": "True"},
    {"text": "Bats are completely blind.", "answer": "False"},
    {"text": "A group of lions is called a pride.", "answer": "True"},
    {"text": "Wombat poop is cube-shaped.", "answer": "True"},
    {"text": "Cows have best friends and get stressed when separated.", "answer": "True"},
    {"text": "Sloths can hold their breath longer than dolphins.", "answer": "True"},
    {"text": "Turtles can leave their shells if they feel cramped.", "answer": "False"},
    {"text": "A snail can sleep for three years.", "answer": "True"},
    {"text": "Octopuses taste with their arms.", "answer": "True"},
    {"text": "Penguins can fly short distances.", "answer": "False"},
    {"text": "A shrimp's heart is located in its head.", "answer": "True"},
    {"text": "Elephants are the only animals that cannot jump.", "answer": "True"},
    {"text": "Sharks are mammals.", "answer": "False"},
    {"text": "A group of flamingos is called a flamboyance.", "answer": "True"},
    {"text": "Crocodiles cannot stick their tongue out.", "answer": "True"},
    {"text": "Humans share about 60% of their DNA with bananas.", "answer": "True"},
    {"text": "Your stomach gets a new lining every week.", "answer": "True"},
    {"text": "You can hum while holding your nose closed.", "answer": "False"},
    {"text": "The human nose can detect over one trillion different scents.", "answer": "True"},
    {"text": "Fingernails grow faster on the hand you write with.", "answer": "True"},
    {"text": "The human body contains enough iron to make a small nail.", "answer": "True"},
    {"text": "Humans use only 10% of their brain.", "answer": "False"},
    {"text": "Babies are born with kneecaps.", "answer": "False"},
    {"text": "The tongue is the strongest muscle in the human body.", "answer": "False"},
    {"text": "Your eyes are the same size from birth to death.", "answer": "True"},
    {"text": "Lightning is seen before it's heard because light travels faster than sound.", "answer": "True"},
    {"text": "Honey doesn't spoil — edible honey has been found in ancient Egyptian tombs.", "answer": "True"},
    {"text": "Hot water freezes faster than cold water.", "answer": "True"},
    {"text": "Diamonds are made of compressed coal.", "answer": "False"},
    {"text": "The Sun is a star.", "answer": "True"},
    {"text": "Venus is the hottest planet in our solar system.", "answer": "True"},
    {"text": "Water expands when it freezes.", "answer": "True"},
    {"text": "Sound travels faster through water than through air.", "answer": "True"},
    {"text": "An atom is the smallest particle in existence.", "answer": "False"},
    {"text": "Potatoes were first cultivated in South America.", "answer": "True"},
    {"text": "The Great Wall of China is visible from space with the naked eye.", "answer": "False"},
    {"text": "The Great Depression began in 1929.", "answer": "True"},
    {"text": "Napoleon Bonaparte was unusually short for his time.", "answer": "False"},
    {"text": "The Eiffel Tower was originally intended to be a temporary structure.", "answer": "True"},
    {"text": "Australia is both a country and a continent.", "answer": "True"},
    {"text": "Russia is the largest country in the world by land area.", "answer": "True"},
    {"text": "The Amazon River flows into the Pacific Ocean.", "answer": "False"},
    {"text": "Cleopatra lived closer in time to the Moon landing than to the construction of the Great Pyramid.", "answer": "True"},
    {"text": "The Czech Republic drinks the most beer per capita in the world.", "answer": "True"},
    {"text": "In Switzerland, it is illegal to own just one guinea pig.", "answer": "True"},
    {"text": "In France, it is legal to marry a deceased person.", "answer": "True"},
    {"text": "In Alaska, USA, it is illegal to wake a sleeping bear to take a photo.", "answer": "True"},
    {"text": "Google was co-founded by Elon Musk.", "answer": "False"},
    {"text": "The first Disney animated feature film was Cinderella.", "answer": "False"},
    {"text": "Nemo from Finding Nemo is a clownfish.", "answer": "True"},
    {"text": "Spider silk was once used to make violin strings.", "answer": "True"},
    {"text": "Coca-Cola is available in every country in the world.", "answer": "False"},
    {"text": "Abraham Lincoln had no middle name.", "answer": "True"},
    {"text": "White chocolate contains no cocoa solids.", "answer": "True"},
    {"text": "Peanuts are technically a type of tree nut.", "answer": "False"},
    {"text": "Strawberries are technically not berries, but bananas are.", "answer": "True"},
    {"text": "Eating carrots can improve your eyesight beyond normal vision.", "answer": "False"},
    {"text": "Apples are more effective at waking you up in the morning than coffee.", "answer": "True"},
]
